runtime: php55
api_version: 1

handlers: 
- url: /images
  static_dir: images
 
- url: /signup.php
  script: signup.php

- url: /main.php
  script: main.php

- url: /newpost.php
  script: newpost.php

- url: /viewpost.php
  script: viewpost.php

- url: /mypost.php
  script: mypost.php

- url: /password.php
  script: password.php

- url: /.* 
  script: login.php
  